# frozen_string_literal: true

source 'https://rubygems.org'
gem 'bcrypt', '~> 3.1.19'
gem 'iostreams', '~> 1.10.3'
gem 'pg', '~> 1.4.3'
gem 'puma', '~> 6.3.0'
gem 'sinatra', '~> 3.0.4'
gem 'sinatra-contrib', '~> 3.0.2'
