source 'https://rubygems.org'
gem 'sinatra', "~> 1.4.7"
gem 'logger', "~> 1.2.8"
gem 'bcrypt', "~> 3.1.11"
gem 'mp3info', "~> 0.8.5"
gem 'pg', "~> 0.18.4"
gem 'warden', "~> 1.2.6"
gem 'rack-cache', :require => 'rack/cache'
gem 'rspec-core'
gem 'rspec'
