source 'https://rubygems.org'
gem 'sinatra', "~> 2.0.4"
gem 'logger', "~> 1.3.0"
gem 'bcrypt', "~> 3.1.13"
gem 'mp3info', "~> 0.8.5"
gem 'pg', "~> 1.1.4"
#gem 'pg', "~> 0.18.4"
gem 'warden', "~> 1.2.6"
gem 'rack-cache', :require => 'rack/cache'
gem 'rack-test'
gem 'rspec-core'
gem 'rack', "~> 2.0.7"
gem 'rspec'
