# frozen_string_literal: true

source 'https://rubygems.org'
gem 'bcrypt', '~> 3.1.19'
gem 'iostreams', '~> 1.10.3'
gem 'net-sftp', '~> 4.0.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.3.0'
gem 'sinatra', '~> 3'
gem 'sinatra-contrib', '~> 3'

gem "rspec", "~> 3.12"
