# frozen_string_literal: true

source 'https://rubygems.org'
gem 'bcrypt', '~> 3.1.19'
gem 'iostreams', '~> 1.10.3'
gem 'net-sftp', '~> 4.0.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4.3'
gem 'rspec', '~> 3.12'
gem 'sinatra', '~> 4'
gem 'sinatra-contrib', '~> 4'
gem 'taglib-ruby', '>= 2'

gem "ed25519", "~> 1.4"

gem "bcrypt_pbkdf", "~> 1.1"
