source 'https://rubygems.org'
gem 'sinatra', "~> 2.0.8.1"
gem 'jwt', "~> 2.2.1"
gem 'logger', "~> 1.4.2"
gem 'mp3info', "~> 0.8.5"
gem 'httparty', "~> 0.18.1"
gem 'pg', "~> 1.2.3"
#gem 'pg', "~> 0.18.4"
gem 'rack-cache', :require => 'rack/cache'
gem 'rack-test'
gem 'rspec-core'
gem 'rack', ">= 2.2.3"
gem 'rspec'
