# frozen_string_literal: true

source 'https://rubygems.org'
gem 'httparty', '~> 0.21.0'
gem 'jwt', '~> 2.5.0'
gem 'logger', '~> 1.4.2'
gem 'pg', '~> 1.4.3'
gem 'bcrypt', '~> 3.1'
gem 'sinatra', '~> 2.2.0'
gem 'taglib-ruby', '~> 1.0.1'
gem 'thin', '~> 1.8.1'
# gem 'pg', "~> 0.18.4"
gem 'rack', '>= 2.2.3.1'
gem 'rack-cache', require: 'rack/cache'
gem 'rack-test'
gem 'rspec'
gem 'rspec-core'
gem 'webrick'
